name: DevOps CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - uat
      - main

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4


    # Detect environment from branch
    - name: Set environment variables
      run: |
        if [[ "${GITHUB_REF##*/}" == "dev" ]]; then
          echo "AWS_ROLE=${{ secrets.DEV_AWS_ROLE }}" >> $GITHUB_ENV
          echo "DEPLOYMENT_NAME=flask-app-dev" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF##*/}" == "uat" ]]; then
          echo "AWS_ROLE=${{ secrets.UAT_AWS_ROLE }}" >> $GITHUB_ENV
          echo "DEPLOYMENT_NAME=flask-app-uat" >> $GITHUB_ENV
        else
          echo "AWS_ROLE=${{ secrets.PROD_AWS_ROLE }}" >> $GITHUB_ENV
          echo "DEPLOYMENT_NAME=flask-app-prod" >> $GITHUB_ENV
        fi


    # Configure AWS credentials (OIDC)
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ env.AWS_ROLE }}
        aws-region: ${{ secrets.AWS_REGION }}


    # Login to ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2


    # Build Docker image
    - name: Build Docker Image
      run: |
        docker build -t flask-app .


    # Tag Docker image
    - name: Tag Docker Image
      run: |
        docker tag flask-app:latest \
        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO }}:${{ github.sha }}


    # Push Docker image
    - name: Push Docker Image
      run: |
        docker push \
        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO }}:${{ github.sha }}


    # Configure kubectl
    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig \
        --name ${{ secrets.EKS_CLUSTER }} \
        --region ${{ secrets.AWS_REGION }}


    # Deploy Kubernetes manifests
    - name: Deploy to Kubernetes
      run: |
        IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO }}:${{ github.sha }}

        sed -i "s|IMAGE_URI|$IMAGE|g" k8s/deployment-dev.yaml

        kubectl apply -f k8s/


    # Verify rollout
    - name: Verify Deployment
      run: |
        kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }}